/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */

import { defineCollection } from '@nocobase/database';
import { idField, statusField } from './logisticsCollectionFields';

export default defineCollection({
  name: 'transport_runs',
  title: 'Рейсы',
  hidden: false,
  template: 'general',
  view: false,
  autoGenId: false,
  createdAt: true,
  createdBy: true,
  updatedAt: true,
  updatedBy: true,
  logging: true,
  titleField: 'run_number',
  filterTargetKey: ['id'],
  migrationRules: ['overwrite', 'schema-only'],
  indexes: [
    { name: 'transport_runs_run_number_unique', unique: true, fields: ['run_number'] },
    { name: 'transport_runs_status_created_at_idx', fields: ['status', 'createdAt'] },
    { name: 'transport_runs_vehicle_id_idx', fields: ['vehicle_id'] },
    { name: 'transport_runs_departure_city_id_idx', fields: ['departure_city_id'] },
  ],
  fields: [
    idField,
    {
      type: 'integer',
      name: 'run_number',
      interface: 'integer',
      allowNull: false,
      uiSchema: {
        type: 'number',
        title: 'Номер рейса',
        'x-component': 'InputNumber',
        'x-read-pretty': true,
      },
    },
    statusField,
    { type: 'bigInt', name: 'vehicle_id', interface: 'integer', isForeignKey: true, allowNull: false, hidden: true },
    {
      type: 'belongsTo',
      name: 'vehicle',
      interface: 'm2o',
      target: 'vehicles',
      targetKey: 'id',
      foreignKey: 'vehicle_id',
      onDelete: 'RESTRICT',
      allowNull: false,
      hidden: true,
      uiSchema: {
        type: 'object',
        title: 'Транспортное средство',
        'x-component': 'AssociationField',
        'x-component-props': {
          multiple: false,
          disabled: true,
          fieldNames: { value: 'id', label: 'registration_number' },
        },
        required: true,
      },
    },
    {
      type: 'virtual',
      name: 'registration_number_input',
      interface: 'input',
      uiSchema: {
        type: 'string',
        title: 'Номер машины',
        'x-component': 'Input',
        required: true,
      },
    },
    { type: 'bigInt', name: 'departure_city_id', interface: 'integer', isForeignKey: true, allowNull: true },
    {
      type: 'belongsToMany',
      name: 'managers',
      interface: 'm2m',
      target: 'users',
      through: 'transport_run_managers',
      sourceKey: 'id',
      targetKey: 'id',
      foreignKey: 'transport_run_id',
      otherKey: 'user_id',
      onDelete: 'CASCADE',
      uiSchema: {
        type: 'array',
        title: 'Менеджеры',
        'x-component': 'AssociationField',
        'x-component-props': { multiple: true, fieldNames: { value: 'id', label: 'nickname' } },
      },
    },
    {
      type: 'belongsToMany',
      name: 'declarants',
      interface: 'm2m',
      target: 'users',
      through: 'transport_run_declarants',
      sourceKey: 'id',
      targetKey: 'id',
      foreignKey: 'transport_run_id',
      otherKey: 'user_id',
      onDelete: 'CASCADE',
      uiSchema: {
        type: 'array',
        title: 'Декларанты',
        'x-component': 'AssociationField',
        'x-component-props': { multiple: true, fieldNames: { value: 'id', label: 'nickname' } },
      },
    },
    {
      type: 'belongsToMany',
      name: 'shipments',
      interface: 'm2m',
      target: 'shipments',
      through: 'transport_run_shipments',
      sourceKey: 'id',
      targetKey: 'id',
      foreignKey: 'transport_run_id',
      otherKey: 'shipment_id',
      onDelete: 'CASCADE',
      uiSchema: {
        type: 'array',
        title: 'Поставки',
        'x-component': 'AssociationField',
        'x-component-props': { multiple: true, fieldNames: { value: 'id', label: 'display_name' } },
      },
    },
    {
      type: 'belongsToMany',
      name: 'parent_runs',
      interface: 'm2m',
      target: 'transport_runs',
      through: 'transport_run_parent_links',
      sourceKey: 'id',
      targetKey: 'id',
      foreignKey: 'child_run_id',
      otherKey: 'parent_run_id',
      onDelete: 'CASCADE',
      uiSchema: {
        type: 'array',
        title: 'Родительские рейсы',
        'x-component': 'AssociationField',
        'x-component-props': { multiple: true, fieldNames: { value: 'id', label: 'run_number' } },
      },
    },
    {
      type: 'belongsToMany',
      name: 'child_runs',
      interface: 'm2m',
      target: 'transport_runs',
      through: 'transport_run_parent_links',
      sourceKey: 'id',
      targetKey: 'id',
      foreignKey: 'parent_run_id',
      otherKey: 'child_run_id',
      onDelete: 'CASCADE',
      uiSchema: {
        type: 'array',
        title: 'Дочерние рейсы',
        'x-component': 'AssociationField',
        'x-component-props': { multiple: true, fieldNames: { value: 'id', label: 'run_number' } },
      },
    },
    {
      type: 'hasMany',
      name: 'history',
      interface: 'o2m',
      target: 'transport_run_history',
      sourceKey: 'id',
      foreignKey: 'transport_run_id',
      targetKey: 'id',
      onDelete: 'CASCADE',
      uiSchema: {
        type: 'array',
        title: 'История',
        'x-component': 'AssociationField',
        'x-component-props': { multiple: true },
      },
    },
  ],
});
